import { ImageRole } from '@/types';

export const ANALYSIS_CATEGORIES = [
  {
    key: 'character' as const,
    icon: '👤',
    titleEs: 'Personaje (Referencia)',
    titleEn: 'Character (Reference)',
    fields: [
      { key: 'celebrityAnchor', labelEs: 'Anclaje Facial', labelEn: 'Facial Anchor' },
      { key: 'ageAndGender', labelEs: 'Edad y Género', labelEn: 'Age and Gender' },
      { key: 'ethnicity', labelEs: 'Etnia/Fenotipo', labelEn: 'Ethnicity/Phenotype' },
      { key: 'faceShape', labelEs: 'Estructura Ósea', labelEn: 'Bone Structure' },
      { key: 'eyesAndBrows', labelEs: 'Ojos y Cejas', labelEn: 'Eyes and Brows' },
      { key: 'nose', labelEs: 'Nariz', labelEn: 'Nose' },
      { key: 'mouthAndJaw', labelEs: 'Boca y Mandíbula', labelEn: 'Mouth and Jaw' },
      { key: 'skinAndComplexion', labelEs: 'Textura de Piel', labelEn: 'Skin Texture' },
      { key: 'hair', labelEs: 'Pelo', labelEn: 'Hair' },
      { key: 'bodyType', labelEs: 'Constitución', labelEn: 'Body Type' },
      { key: 'clothing', labelEs: 'Ropa', labelEn: 'Clothing' },
      { key: 'distinctiveTraits', labelEs: 'Micro-Detalles', labelEn: 'Micro-Details' },
    ],
  },
  {
    key: 'pose' as const,
    icon: '🚶‍♂️',
    titleEs: 'Pose y Acción',
    titleEn: 'Pose & Action',
    fields: [
      { key: 'action', labelEs: 'Acción', labelEn: 'Action' },
      { key: 'bodyLanguage', labelEs: 'Lenguaje Corporal', labelEn: 'Body Language' },
      { key: 'interaction', labelEs: 'Interacción', labelEn: 'Interaction' },
      { key: 'framing', labelEs: 'Encuadre Original', labelEn: 'Original Framing' },
      { key: 'cameraAngle', labelEs: 'Ángulo Original', labelEn: 'Original Angle' },
    ],
  },
  {
    key: 'settingOverride' as const,
    icon: '🏞️',
    titleEs: 'Entorno (Referencia)',
    titleEn: 'Setting (Reference)',
    fields: [
      { key: 'location', labelEs: 'Ubicación', labelEn: 'Location' },
      { key: 'environment', labelEs: 'Entorno/Paisaje', labelEn: 'Environment' },
      { key: 'timeOfDay', labelEs: 'Hora del Día', labelEn: 'Time of Day' },
      { key: 'weather', labelEs: 'Clima', labelEn: 'Weather' },
      { key: 'backgroundElements', labelEs: 'Elementos de Fondo', labelEn: 'Background Elements' },
    ],
  },
  {
    key: 'composition' as const,
    icon: '📐',
    titleEs: 'Composición',
    titleEn: 'Composition',
    fields: [
      { key: 'mainSubject', labelEs: 'Sujeto Principal', labelEn: 'Main Subject' },
      { key: 'secondaryElements', labelEs: 'Elementos Secundarios', labelEn: 'Secondary Elements' },
      { key: 'setting', labelEs: 'Escenario', labelEn: 'Setting' },
      { key: 'framing', labelEs: 'Encuadre', labelEn: 'Framing' },
      { key: 'cameraAngle', labelEs: 'Ángulo de Cámara', labelEn: 'Camera Angle' },
      { key: 'perspective', labelEs: 'Perspectiva', labelEn: 'Perspective' },
      { key: 'compositionalRules', labelEs: 'Reglas Compositivas', labelEn: 'Compositional Rules' },
      { key: 'depthOfField', labelEs: 'Profundidad de Campo', labelEn: 'Depth of Field' },
      { key: 'aspectRatio', labelEs: 'Relación de Aspecto', labelEn: 'Aspect Ratio' },
      { key: 'negativeSpace', labelEs: 'Espacio Negativo', labelEn: 'Negative Space' },
    ],
  },
  {
    key: 'lighting' as const,
    icon: '💡',
    titleEs: 'Iluminación',
    titleEn: 'Lighting',
    fields: [
      { key: 'type', labelEs: 'Tipo', labelEn: 'Type' },
      { key: 'direction', labelEs: 'Dirección', labelEn: 'Direction' },
      { key: 'quality', labelEs: 'Calidad', labelEn: 'Quality' },
      { key: 'intensity', labelEs: 'Intensidad', labelEn: 'Intensity' },
      { key: 'colorTemperature', labelEs: 'Temperatura de Color', labelEn: 'Color Temperature' },
      { key: 'timeOfDay', labelEs: 'Hora del Día', labelEn: 'Time of Day' },
      { key: 'specialEffects', labelEs: 'Efectos Especiales', labelEn: 'Special Effects' },
      { key: 'shadows', labelEs: 'Sombras', labelEn: 'Shadows' },
      { key: 'reflections', labelEs: 'Reflejos', labelEn: 'Reflections' },
    ],
  },
  {
    key: 'colorPalette' as const,
    icon: '🎨',
    titleEs: 'Paleta de Colores',
    titleEn: 'Color Palette',
    fields: [
      { key: 'colorScheme', labelEs: 'Esquema Cromático', labelEn: 'Color Scheme' },
      { key: 'saturation', labelEs: 'Saturación', labelEn: 'Saturation' },
      { key: 'contrast', labelEs: 'Contraste', labelEn: 'Contrast' },
      { key: 'temperature', labelEs: 'Temperatura', labelEn: 'Temperature' },
      { key: 'colorAccents', labelEs: 'Acentos de Color', labelEn: 'Color Accents' },
      { key: 'emotionalConnection', labelEs: 'Conexión Emocional', labelEn: 'Emotional Connection' },
    ],
  },
  {
    key: 'artisticStyle' as const,
    icon: '🖌️',
    titleEs: 'Estilo Artístico',
    titleEn: 'Artistic Style',
    fields: [
      { key: 'medium', labelEs: 'Medio', labelEn: 'Medium' },
      { key: 'artMovement', labelEs: 'Movimiento Artístico', labelEn: 'Art Movement' },
      { key: 'visualAesthetic', labelEs: 'Estética Visual', labelEn: 'Visual Aesthetic' },
      { key: 'photographyStyle', labelEs: 'Estilo Fotográfico', labelEn: 'Photography Style' },
      { key: 'visibleTechniques', labelEs: 'Técnicas Visibles', labelEn: 'Visible Techniques' },
      { key: 'artistInfluence', labelEs: 'Influencia de Artista', labelEn: 'Artist Influence' },
      { key: 'detailLevel', labelEs: 'Nivel de Detalle', labelEn: 'Detail Level' },
      { key: 'rendering', labelEs: 'Renderizado', labelEn: 'Rendering' },
    ],
  },
  {
    key: 'mood' as const,
    icon: '🎭',
    titleEs: 'Atmósfera',
    titleEn: 'Mood',
    fields: [
      { key: 'primaryEmotion', labelEs: 'Emoción Principal', labelEn: 'Primary Emotion' },
      { key: 'energy', labelEs: 'Energía', labelEn: 'Energy' },
      { key: 'narrativeTone', labelEs: 'Tono Narrativo', labelEn: 'Narrative Tone' },
      { key: 'ambientConditions', labelEs: 'Condiciones Ambientales', labelEn: 'Ambient Conditions' },
      { key: 'temporalFeeling', labelEs: 'Sensación Temporal', labelEn: 'Temporal Feeling' },
      { key: 'subjectExpression', labelEs: 'Expresión del Sujeto', labelEn: 'Subject Expression' },
    ],
  },
  {
    key: 'textures' as const,
    icon: '🧱',
    titleEs: 'Texturas y Materiales',
    titleEn: 'Textures & Materials',
    fields: [
      { key: 'identifiedMaterials', labelEs: 'Materiales', labelEn: 'Materials' },
      { key: 'surfaceProperties', labelEs: 'Propiedades de Superficie', labelEn: 'Surface Properties' },
      { key: 'materialState', labelEs: 'Estado del Material', labelEn: 'Material State' },
      { key: 'patterns', labelEs: 'Patrones', labelEn: 'Patterns' },
      { key: 'microDetails', labelEs: 'Micro Detalles', labelEn: 'Micro Details' },
      { key: 'reflectivity', labelEs: 'Reflectividad', labelEn: 'Reflectivity' },
    ],
  },
  {
    key: 'technical' as const,
    icon: '📷',
    titleEs: 'Parámetros Técnicos',
    titleEn: 'Technical Parameters',
    fields: [
      { key: 'apparentResolution', labelEs: 'Resolución', labelEn: 'Resolution' },
      { key: 'simulatedLens', labelEs: 'Lente Simulado', labelEn: 'Simulated Lens' },
      { key: 'estimatedAperture', labelEs: 'Apertura Estimada', labelEn: 'Estimated Aperture' },
      { key: 'grainNoise', labelEs: 'Grano/Ruido', labelEn: 'Grain/Noise' },
      { key: 'postProcessing', labelEs: 'Post-Procesado', labelEn: 'Post-Processing' },
      { key: 'motionBlur', labelEs: 'Motion Blur', labelEn: 'Motion Blur' },
    ],
  },
  {
    key: 'narrative' as const,
    icon: '🏗️',
    titleEs: 'Elementos Narrativos',
    titleEn: 'Narrative Elements',
    fields: [
      { key: 'impliedStory', labelEs: 'Historia Implícita', labelEn: 'Implied Story' },
      { key: 'symbolism', labelEs: 'Simbolismo', labelEn: 'Symbolism' },
      { key: 'culturalContext', labelEs: 'Contexto Cultural', labelEn: 'Cultural Context' },
      { key: 'interaction', labelEs: 'Interacción', labelEn: 'Interaction' },
      { key: 'scale', labelEs: 'Escala', labelEn: 'Scale' },
    ],
  },
];

export const ROLES_CONFIG: { role: ImageRole; icon: string; titleEs: string; titleEn: string; descEs: string; descEn: string; required: boolean }[] = [
  { role: 'base', icon: '🎨', titleEs: '1. Estilo / Escena Base', titleEn: '1. Base Style / Scene', descEs: 'Obligatorio. Define la luz, fondo y estilo global.', descEn: 'Required. Defines lighting, background and global style.', required: true },
  { role: 'character', icon: '👤', titleEs: '2. Personaje (Opcional)', titleEn: '2. Character (Optional)', descEs: 'Extrae cara, pelo y ropa.', descEn: 'Extracts face, hair and clothing.', required: false },
  { role: 'pose', icon: '🏃‍♂️', titleEs: '3. Pose (Opcional)', titleEn: '3. Pose (Optional)', descEs: 'Extrae postura, acción y encuadre.', descEn: 'Extracts posture, action and framing.', required: false },
  { role: 'setting', icon: '🏞️', titleEs: '4. Entorno (Opcional)', titleEn: '4. Setting (Optional)', descEs: 'Sustituye el paisaje o fondo base.', descEn: 'Replaces the base landscape or background.', required: false },
  { role: 'atmosphere', icon: '🎬', titleEs: '5. Atmósfera / Color (Opcional)', titleEn: '5. Atmosphere / Color (Optional)', descEs: 'Extrae la luz, color grading y tono cinemático.', descEn: 'Extracts lighting, color grading and cinematic tone.', required: false },
];
